import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/girl.jpg";
// import code from "../public/code.png";
// import design from "../public/design.png";
// import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kshitija Ghate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Kshitija Ghate</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-violet-500 text- to-purple-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-3xl py-2 leading-2 text-violet-600 font-medium dark:text-purple-400 md:text-6xl">
              Welcome to My Personal Portfolio
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Front-End and Back-End Development
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            If you're looking for a web developer who can bring your ideas to life, look no further. 
            Contact me today to get started on your next project!
            </p>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Work Samples</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Having worked at <span className="text-violet-500"> Cognizant </span> and a startup <span className="text-violet-500"> The Earth Lovers </span>, I bring with me valuable web development experience. 
            Feel free to browse through my latest work.

            </p>
          </div>
          <div className="lg:flex gap-10">
            
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gradient-to-r from-violet-50 text- to-purple-50  dark:bg-violet-50 flex-1">
              <a href="https://theearthloversindia.com"><Image src={web1}  /></a>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                E-Commerce Application
              </h3>
              {/* <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p> */}
              <h4 className="py-4 text-violet-600">Technologies Used</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Angular</p>
              <p className="text-gray-800 py-1">Django</p>
            </div>
            
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gradient-to-r from-violet-50 text- to-purple-50 dark:bg-violet-50 flex-1">
              <a href="https://stingray-app-insha.ondigitalocean.app/"><Image src={web2}  /></a>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
              High-end Cosmetics Website
              </h3>
              {/* <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p> */}
              <h4 className="py-4 text-violet-600">Technologies Used</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">React JS</p>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-gradient-to-r from-violet-50 text- to-purple-50 dark:bg-violet-50 flex-1">
              <a href="https://tech.kshitijaghate.com/"><Image src={web3}  /></a>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Modern Technology App</h3>
              {/* <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p> */}
              <h4 className="py-4 text-violet-600">Technologies Used</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">React JS</p>
              
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Technologies</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I possess expertise in modern front-end frameworks like <span className="text-violet-500"> Angular </span> and
            <span className="text-violet-500"> React JS </span>,
            as well as proficiency in back-end frameworks such as Django and Django REST Framework.
            </p>

          </div>
          <div className="lg:flex gap-10">
            <div className="text-center p-10 rounded-xl my-10  dark:text-gray-200 flex-1">
            
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Front-End
              </h3>
              <p className="py-2">
                Experience with React JS, Angular
              </p>
              

            </div>
            <div className="text-center p-10 rounded-xl my-10 dark:text-gray-200 flex-1">
              
              <h3 className="text-lg font-medium pt-8 pb-2 ">
              Back-End
              </h3>
              <p className="py-2">
              Experience working with Python, Django Framework, and Databases like PostgreSQL, MySQL
              </p>
              

              
            </div>
            <div className="text-center p-10 rounded-xl my-10 dark:text-gray-200 flex-1">
              
              <h3 className="text-lg font-medium pt-8 pb-2 ">UI/UX</h3>
              <p className="py-2">
                Experience with tools like Figma
              </p>
            

              
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Gallery</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
        <section >
          <div  >
            <h3 className="mb-8 text-3xl dark:text-white ">Contact Info</h3>
            <h4 className=" text-violet-600">Email</h4>
            <p className="mb-8 text-md  leading-8 text-gray-800 dark:text-gray-200">
            kshitija17@live.com</p>
            </div>
        </section>

      </main>
    </div>
  );
}
